live_config_reload = true

import = [ 
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/catppuccin_frappe.toml"
]

[window]
opacity = 1.0
decorations = "None"
padding = { x = 0, y = 0}

[font]
size = 16.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
builtin_box_drawing = true
